name: example
description: nimble_charts Demo
homepage: https://github.com/Nimblesite/nimble_charts
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  flutter_test:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.1.1
  nimble_charts:
    path: ../
flutter:
  uses-material-design: true
dev_dependencies:
  austerity: ^1.2.0
