name: nimble_charts
version: 0.5.0-beta
description: Charts for Flutter. A fork of charts_flutter
homepage: https://github.com/Nimblesite/nimble_charts
publish_to: 'none' 

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.14.5
  flutter:
    sdk: flutter
  meta: ^1.1.1
  nimble_charts_common:
    path: ../charts_common

dev_dependencies:
  austerity: ^1.2.0
  build_runner: ^2.4.12
  example:
    path: example
  flutter_staggered_animations: ^1.1.1
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  test: ^1.3.0

